### ISSUE TITLE
Emails favor quick popularity over steady growth

### ISSUE THREAD

**Issue by timboudreau** [thechangelog/nightly#10]
One thing that is annoying is that, if you have a project that slowly and steadily grows stars, you will never show up in this list.  So it favors, not projects that are necessarily most valuable, but projects which initially get a lot of attention.

This is not just an easy stat to game (whenever I open source something I must email all my friends to please star it now, which is weird and annoying), but also one that means many useful projects will never be seen here.

It would be nice if you added a category for "long tail" projects - ones that didn't necessarily make an initial huge splash, but have shown steady gains over time and have not been listed before.

**Comment by adamstac** [comment]
@timboudreau thanks for sharing your thoughts here. It's very helpful to see your perspective when thinking about what we're doing here.

I will say that is just a start for us. We have plans for more ways to present interesting data to help folks keep up. We also don't want to be a GitHub explore me too of sorts.

With Changelog Nightly, we took what GitHub Archive had done already well, redesigned it to a more presentable version, made it look great on mobile, and updated the content and presentation to fine tune its readability.

I'll let @jerodsanto weigh in with his thoughts around this. He's working on a project (totally heads down) right now, so expect a response back next week sometime.

**Comment by jerodsanto** [comment]
@timboudreau I definitely see what you mean. 

While I agree that it'd be easy to game Nightly (especially on the weekends when there's less new repos and activity in general), the advantage of doing so is minimal. So minimal, I believe, that it's unlikely to be a big problem for us.

That being said, it'd be awesome if we could shine a light on "slow and steady" growth repos as well. I'm not sure if Nightly is the place to do that, though. We have [many](http://thechangelog.com) [different](http://thechangelog.com/weekly) [avenues](/thechangelog/ping/issues) which we can use to discover and shine light on those projects.

Adding this to Nightly would require much heavier lifting than we're currently doing. I'm not saying it wouldn't be worth it, just that I'm not sure at this point.

**Comment by timboudreau** [comment]
So I'm guessing there's no retained state between nightly runs?

The way I'd do it would be something like:
 - Retain a list of all seen projects and their star count, by date - could
be as simple as a flat file with lines like 'joeshmoe/foo:23' named by date
- no need to get fancy
 - Each night, compare the star count with what it was, say, 30/60/90 days
ago
 - Anything that is above some threshold number gets a mention

A project that gains popularity slowly is just as likely to be interesting
as one that hit rapidly - and that would balance out the ADDishness - after
all, 100 stars means the same thing whether they were gained in a day or a
year, and not every project owner is tremendously skilled at marketing
their work.


On Sun, Mar 1, 2015 at 10:08 AM, Jerod Santo <notifications@github.com>
wrote:

> @timboudreau <https://github.com/timboudreau> I definitely see what you
> mean.
>
> While I agree that it'd be easy to game Nightly (especially on the
> weekends when there's less new repos and activity in general), the
> advantage of doing so is minimal. So minimal, I believe, that it's unlikely
> to be a big problem for us.
>
> That being said, it'd be awesome if we could shine a light on "slow and
> steady" growth repos as well. I'm not sure if Nightly is the place to do
> that, though. We have many <http://thechangelog.com> different
> <http://thechangelog.com/weekly> avenues
> <http:///thechangelog/ping/issues> which we can use to discover and shine
> light on those projects.
>
> Adding this to Nightly would require much heavier lifting than we're
> currently doing. I'm not saying it wouldn't be worth it, just that I'm not
> sure at this point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/nightly/issues/10#issuecomment-76600667>.
>



-- 
http://timboudreau.com

**Comment by daniellmb** [comment]
I wonder if any other metrics could help the nightly list be less of a popularity contest (aka the number of stars in a given day). Such as looking at contributor and fork counts as a signal for community involvement and commits and releases as the pulse for repo activity.

**Comment by timboudreau** [comment]
That would be good.  I think the challenge here is that there's what's
easy-to-measure and there's what's actually interesting, and they aren't
always the same thing.

On Wed, Mar 4, 2015 at 11:44 AM, Daniel Lamb <notifications@github.com>
wrote:

> I wonder if any other metrics could help the nightly list be less of a
> popularity contest (aka the number of stars in a given day). Such as
> looking at contributor and fork counts as a signal for community
> involvement and commits and releases as the pulse for repo activity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/nightly/issues/10#issuecomment-77194464>.
>



-- 
http://timboudreau.com

**Comment by jerodsanto** [comment]
We appreciate your thoughts and feedback on this, but ultimately, I don't believe this change is worth the effort involved. 🍻
