### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by scanf** [thechangelog/nightly#11]
Just got my first nightly email :) emojis do not seem to display properly. In the email for Feb 28 on entry karan/joe you can see that the emoji is not displayed, but the text is shown. Would be nice if nightly would support emojis like Github does.

**Comment by jerodsanto** [comment]
YES! I noticed this last night, too. We're already doing some (hacky) [pre-processing](https://github.com/thechangelog/nightly/blob/master/lib/bq_client.rb#L39) on the descriptions, so it'd make sense to plug emoji support in there.

We might even consider pulling in [html-pipeline](https://github.com/jch/html-pipeline) to handle this stuff.

**Comment by adamstac** [comment]
@scanf we aren't going to resend the email but the archived issue has the emoji now http://nightly.thechangelog.com/2015/02/28/

Thanks for reminding us to add support for it.
