### ISSUE TITLE
Custom domain email addresses invalid.

### ISSUE THREAD

**Issue by noahmorrison** [thechangelog/nightly#14]
I have a custom domain for my email <noah at morrison dot ph> which is not considered a valid email. Which means I can't sign up for the newsletter.

This is the only email I've tried it with, so it might just be emails at a custom TLD. I'm not exactly sure as I don't know where the email validation code is, so I can't look into it.

**Comment by jerodsanto** [comment]
Weird. The list sign up is run via Campaign Monitor, so they are the ones doing the email validation. If you send us your email address (editors@changelog.com if you don't want to post it here) we can try to run it down with the Campaign Monitor folks.

**Comment by noahmorrison** [comment]
My email is <noah@morrison.ph>, I thought I put it in the original issue, but I guess not.

**Comment by adamstac** [comment]
Hey @noahmorrison I tested it and was able to add you both inside Campaign monitor directly as well as at http://thechangelog.com/nightly

Onsite we use the jQuery Validation plugin (v1.11.1), but I was able to submit your email fine onsite too.

Can you tell us more about the error you saw?

**Comment by noahmorrison** [comment]
I just tried again (But from a different device) and it also worked.

When I get home I'll try again with the device I was trying with before.

**Comment by noahmorrison** [comment]
I got home and tried it again on my nexus 7 like this morning, still invalid...
![screenshot_2015-03-03-14-59-33](https://cloud.githubusercontent.com/assets/7417485/6471076/2344cc36-c1b6-11e4-9d57-0c681c265a1d.png)
![screenshot_2015-03-03-14-59-40](https://cloud.githubusercontent.com/assets/7417485/6471081/2c809c80-c1b6-11e4-885f-bad95d67b4a0.png)

It also works on my laptop, however I still am not receiving a confirmation email. I did it earlier (10 AMish) at work, and just tried again but i still haven't gotten one (I've checked the spam filter).

Is there a better place to open an issue about this? Or is this fine?

**Comment by adamstac** [comment]
@noahmorrison you're good to go. I subscribed you manually. If for reason you don't get Changelog Nightly tonight, head back here and we'll reopen the issue.

I'm not sure why CM is saying your email is invalid only on your Nexus. Sorry about that!
