### ISSUE TITLE
plaintext or light background version?

### ISSUE THREAD

**Issue by zeke** [thechangelog/nightly#15]
First off, thanks for reviving this project. I've been a long-time fan of the github archive emails, and I'm glad someone is picking up the slack.

But... I don't like the styles. I get that it's dark because it's "the nightly", but the thematic cuteness wears off when when I start reading the email. It's only dark email I get, and my eyes struggle to adjust.

Would you accept a PR for a light version, or perhaps a plaintext version?

**Comment by jerodsanto** [comment]
Zeke-

We feel you on the night theme. A day theme is on our hit list (near the top).

-Jerod
(sent on the go)

**Comment by adamstac** [comment]
@zeke @jerodsanto I'm opening issue #16 so we can gather feedback from others as well. We've gotten a few comments on the design update so I want to make sure we hear from others on our design choice so we can refine the design and ship something everyone loves.

@zeke if you can re-comment there, that'd be awesome and appreciated.
