### ISSUE TITLE
Design feedback welcomed and wanted

### ISSUE THREAD

**Issue by adamstac** [thechangelog/nightly#16]
We’ve gotten several emails and notes from folks about the design update in the transition from GitHub Archive to Changelog Nightly. We hear you, and the point of this issue to gather from feedback from those who may have not emailed or gotten in touch about the design update.

Here are the particular areas of comment so far:

- The dark background (aka the night theme) - It’s nice, but hard to adjust on the eyes. Some have mentioned it’s harder to read.
- The repo level layout is less dense and less list like, and therefore harder to scan. Some have asked for a plain text version instead.
- In general its less simple — it was more news ticker before vs now it’s like sitting down with a newspaper

We want the community to know that we are all ears on making the design and UX of reading Changelog Nightly the best it can be.

Help us come to a consensus on layout and design thoughts so we can get back to work refining the design and shipping the best nightly email we can.

Thanks!

**Comment by adamstac** [comment]
For reference -- here's a screenshot of GitHub Archive and Changelog Nightly.

![github archive - jan 21](https://cloud.githubusercontent.com/assets/2933/6528761/eeaefe02-c3e9-11e4-9bf7-01230aa8a2b2.png)

![changelog nightly - march 4](https://cloud.githubusercontent.com/assets/2933/6528766/f65be57a-c3e9-11e4-966f-53dfaccf4ae6.png)

**Comment by pastjean** [comment]
For people that want to see or lost the email : http://nightly.thechangelog.com/2015/02/25/

Here is my take on the design review. 

I kinda like the dark nightly theme, makes things different and sure it not on current design trends to have a dark background email I like the fact that it is different.

- The dark background could be darker and would make it possible to make the white text a little more grey (less agressive on the eyes)
- The white text could be greyer (is that even a word)
- For more list like try putting the arrow and stars on the right of the project title
- I like the fact that it looks more like a news paper but in between both it would be nice

Have a look at my take:
![image](https://cloud.githubusercontent.com/assets/140675/6528835/c2104ca8-c3f2-11e4-93f6-808008539364.png)

- Darker background
- More list like
- Less newspapery but still has white space.

**Comment by adamstac** [comment]
@pastjean the only issue with the star counts on the same line as the title is that you won't be able to scan them as easily because the titles are variable in length.

**Comment by pastjean** [comment]
I agree on the scanning part!
Could place stars on the left of the title and let the language on the right , would make scanning easier. (language is variable length so after title). The title would always be at the same place horizontally and there would still be one less line.

Finding a way to remove one line would make things more listy and easier to scan.

**Comment by samyakbhuta** [comment]
* +1 on making repository title font less white.
* Though I like the black background, the accompanying gravatar/profile picture is not always suitable for  the black background. e.g. vektra/templar, impertio/blogs in March 6th issue. I guess most of the Github users optimises these picture for Github website, which is predominantly white.

**Comment by adamstac** [comment]
Here's a light version that's more concise.

![changelog-nightly-light-concise](https://cloud.githubusercontent.com/assets/2933/6530482/e6503ba6-c3f6-11e4-9394-deb5f7cd4eee.png)

**Comment by zeke** [comment]
:shipit:

**Comment by jerodsanto** [comment]
We're :ship:ing an updated design tonight based on this feedback. 

Also! We've added a Day theme for those who prefer that. You can switch themes by clicking the "Manage your preferences" link at the bottom of tonight's email.

Thanks for the input everyone! Let us know what you think of the changes! :beers:

**Comment by zeke** [comment]
:sunglasses:

**Comment by adamstac** [comment]
Closing, because #18.

Thanks for all the feedback :beers:
