### ISSUE TITLE
Group or sort results by language

### ISSUE THREAD

**Issue by zeke** [thechangelog/nightly#17]
I hate to admit it, but I _mostly_ only care about the javascript stuff these days. It might be interesting to see a version of the nightly grouped (or even just sorted) by language.

**Comment by jerodsanto** [comment]
@zeke thanks for the input! We've definitely been thinking about this. For Nightly as it currently stands, I think sorting by most stars is the way to go.

However, we'd LOVE to do language-specific editions so you can just get the content you're interested in and nothing else.

I'm going to close this issue for now, but keep a watch on this repo as we make moves in this direction. :beers:
