### ISSUE TITLE
Include GitLab projects

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/nightly#21]
Interesting idea from @kujua (https://github.com/thechangelog/ping/issues/450).

I would love to make this a reality, but I'm not sure if GitLab exposes the information we need to include them. @kujua would you mind doing some groundwork to see if it's even feasible at this point?

**Comment by kujua** [comment]
Yes, will have a look at GitLab's API and report back.

**Comment by kujua** [comment]
There is an API call that returns all projects: _https://gitlab.com/api/v3/projects/all_, similar to GitHub's API.

There are two problems:
- All calls are authenticated with a private key and it needs an adminstrator account to access this API function.
- The search criteria does not seem to support searching by date, so it seems that the whole list is returned. the good news: the list can be ordered by date (creation, updated, last activity). 

The returned JSON has a field "star_count", so the statistics would be easy to compile.

I doubt a normal user gets access with an admin account, but you could try. I guess it would be in GitLab's interest to be exposed in a daily email.

Hope this helps.

**Comment by jerodsanto** [comment]
@kujua I think the biggest problem is that `star_count` won't get us where we need to go. What we really need is `new_star_count_in_the_last_24_hours`. The GitHub API doesn't expose this either, which is why we use [GitHub Archive](https://www.githubarchive.org) instead.

We would probably have to work closely with the GitLab team to accomplish something like this. Who do you think would be the best person to talk to about it?

**Comment by kujua** [comment]
No idea who could help. Will ask in their forum.

**Comment by kujua** [comment]
Asked in the forum some days ago (https://forum.gitlab.com/t/get-statistics-starred-forked-for-all-projects/2852), but nobody responded. I guess it is not possible to do that without the help of the GitLab admins...

**Comment by jerodsanto** [comment]
@kujua that's too bad. We haven't been able to form a relationship with the GitLab team yet. If/when we do, this'll be a topic I bring up as a way we could work together with them. 

Closing this issue for now, since it's not currently possible. Thanks for the great suggestion and for being part of the Changelog community. ✊

**Comment by dosire** [comment]
I've opened up an issue in the CE issue tracker https://gitlab.com/gitlab-org/gitlab-ce/issues/22386
