### ISSUE TITLE
Provide a weekly report

### ISSUE THREAD

**Issue by rmartin** [thechangelog/nightly#23]
I really enjoy the insights provided in this email and have discovered a lot of new repositorizes. However,  I find the frequency a bit challenging to keep up with inbox zero. I'd love to have a weekly digest or rollout report. Ideally that'd be a consolidated list of the repositories that trended during the week. This could then be configured to send out on a specific day of the week so you could get the previously 7 days on the day that was most convenient for you. I'd be happy to help evaluate how this could be done if this is something your interested in pursuing. 

Thanks for providing a great resource and podcast to the community. 

Cheers,
Roy

**Comment by jerodsanto** [comment]
@rmartin thanks for the idea! A few thoughts/questions:

1. You do know that we have a [weekly](https://changelog.com/weekly) email, right? It's not what you're suggesting, but you should still subscribe to it. 😜
2. How would the aggregation work? Would we still limit each list to N repos (and nudge out the ones that had less stars), or would we simply include all repos that made the 7 nightly lists?
3. I also wonder how useful a monthly version would be...

**Comment by rmartin** [comment]
hey @jerodsanto,

Thanks for the prompt reply. Please find my feedback below. 

1. Weekly List - I believe you have mentioned it on the show in the past but I had forgotten about that. I'm signed-up now and looking forward to the update. 
2. Aggregation - Honestly, I think both could be a potential solution. Perhaps the MVP could be whatever is the least amount of engineering effort to accomplish and then if it was a popular option it could be built up further to offer more support. Having all N repos is that it would be a 'true' rollup, so you wouldn't miss anything from the nightly. However, having the filtered limit similar to the current report would provide a consistency and a synopsis that didn't become overwhelming. 
3. Monthly - I'm not too familiar with how you've configured this with campaign monitor. Would these need to be separate lists and processes for each of the options? I.E. one list for nightly, another for weekly and another for monthly? Might almost be too infrequent to remember that you were subscribed to it. 

If this is something that you're interested in pursuing let me know. My Ruby chops are not as strong as my Node chops but perhaps I could add value by at least trying to pull together the Google Big Query to help filter that down. Happy to help if i can, and again thanks so much for providing a valuable resource and podcast for the community.

Cheers,
Roy

**Comment by jerodsanto** [comment]
Roy–

Thanks for the thoughtful considerations. My responses:

1. I hope you enjoy Weekly! Let us know if and how we can improve that one as well.
2. I think a true rollup (deduped, of course) would probably provide the most value and wouldn't overwhelm.
3. They'd have to be separate lists, which is fine. However, my biggest concern around this is brand dilution and confusion. We currently have two newsletters: Nightly and Weekly. Pretty straight forward. Now we'd be adding a Weekly version of Nightly. What would we call it? How would we tell people about it? Et cetera.

We have a few possible naming changes in the works that may alleviate the branding problem, so I'm probably not going to pursue this until those take place.

In the meantime, we _do_ keep publicly available data dumps for each night's issue. If you're really motivated to solve this problem you could consume those from Node and set up your own summary newsletter using [Mailtrain](https://mailtrain.org) (or a newsletter service). Last night's data:

http://nightly.changelog.com/2016/06/15/data.json

If you end up setting something up, I'd be happy to help spread the word about it (and I might even subscribe).

**Comment by rmartin** [comment]
hey @jerodsanto ,

Thanks very much, that JSON is very informative, thanks for sharing. I've got a vacation coming up in the next two weeks, so i'll use that time when I have a few moments to play around with this data. It maybe interesting to just have a dashboard that parses the data and displays it outside of an email. That would allow for a little more flexibility. In either case, I'll give that a look and i'll keep you posted. 

Thanks again!
Cheers,
Roy

**Comment by jerodsanto** [comment]
@rmartin yes! 

Adam and I have long believed that some kind of browsable interface for Nightly would be great (we just haven't had the time to build it). Perhaps it could let you move forward/backward through time in some interesting way and see the repos moving in/out of the top lists.

Holler back when you have something you like. If we like it too, we could even integrate it and have it be the homepage at nightly.changelog.com (which is currently just a redirect)

🍻
