### ISSUE TITLE
Only show repos in recipients native language

### ISSUE THREAD

**Issue by Decagon** [thechangelog/nightly#24]
I'd like to have an option to set my native language so that GitHub repos in the newsletter having Chinese/Japanese/Mandarin descriptions aren't shown, because I can't read it.

Alternatively, translate the description into a language that the user can read.

**Comment by jerodsanto** [comment]
@Decagon thanks for the suggestion! This feature is prohibitively difficult to implement<sup>1</sup> commensurate to the value it would provide. I, too, sometimes wonder what those eastern language descriptions are saying. When I'm really intrigued, I'll copy/paste the text in to Google Translate to see. You'll have to do that as well, for the foreseeable future.

Thanks for reading. Thanks for caring! 🍻 

1: we currently send two versions of the email, a Day theme and a Night theme. The way Campaign Monitor is set up, If we allow further customization than that, we'll have to send a different version of the email for each subscriber. We're not ready to do that if it can be avoided.
