### ISSUE TITLE
Why did you publish the "eeeeee" library?

### ISSUE THREAD

**Issue by justinsisley** [thechangelog/nightly#29]
http://email.changelog.com/t/t-l-omkyud-iiitujldk-jh

Really?

<img width="1357" alt="screen shot 2018-11-08 at 9 51 15 pm" src="https://user-images.githubusercontent.com/951765/48245969-61cf9000-e3a2-11e8-92e1-2a4c255f2f2d.png">

**Comment by jerodsanto** [comment]
The bigger question is... how'd they get so many stars yesterday?! 😆

I guess we should add a filter for repos that have super long names. I'm on it!

**Comment by jerodsanto** [comment]
I also regenerated the page in the archive so that repo is no longer there:

http://nightly.changelog.com/2018/11/08/

💚💚💚

**Comment by justinsisley** [comment]
Thank you!
