### ISSUE TITLE
Question : How to submit a repo to be included in the nightly 

### ISSUE THREAD

**Issue by anwarchk** [thechangelog/nightly#32]
Just wondering how do I submit a repo to be included in the nightly email DL ?

**Comment by jerodsanto** [comment]
👋 @anwarchk! Nightly is auto-generated using the number of stars repos receive on a given day. So, you can't submit a repo to be included. You just have to get a bunch of stars in the same 24-hour period and that would do it.

You _can_ submit your stuff to [Changelog News](https://changelog.com/news/submit), though. The most interesting news items will then be included in [Changelog Weekly](https://changelog.com/weekly).

**Comment by anwarchk** [comment]
Thank you so much for the prompt reply @jerodsanto
