### ISSUE TITLE
Night mode background colour incorrect in GMail iPad

### ISSUE THREAD

**Issue by sesh** [thechangelog/nightly#35]
When Dark Mode is enabled on iOS the background colour becomes light, unsure of cause.

iPadOS Dark mode enabled:
![2F363A59-B871-4836-82D1-9AE7ABB18FC5](https://user-images.githubusercontent.com/59980/83476326-c6e25d80-a4d3-11ea-9082-e518c840fef9.png)

IPadOS Dark mode disabled
![8C9FC2AB-9491-4347-A792-99BF00E945A2](https://user-images.githubusercontent.com/59980/83476300-b16d3380-a4d3-11ea-8d1c-a89250fe789c.png)

**Comment by jerodsanto** [comment]
@codyjames can you take a look at this when you have some free time? 🙏

**Comment by codyjames** [comment]
I don't think we _can_ fix it at the moment. More info here: https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers/

![Screen Shot 2020-06-02 at 10 24 54 AM](https://user-images.githubusercontent.com/378665/83550257-6d6e3480-a4bb-11ea-91b4-277407ed7bdd.png)
