### ISSUE TITLE
Changelogs Nightly Email Newsletter

### ISSUE THREAD

**Issue by TitasDas** [thechangelog/nightly#41]
There are a couple of github repos that show up as part of the "new repos" but are actually not active repos or codebases. Just wanted to bring this to everyone's attention and perhaps also educate myself about what these repos might actually be. However in case adding or introducing filters of some kind can take care of this, please introduce them. 

Sharing an example screenshot of these repos - 
![Screenshot 2023-07-12 105707](https://github.com/thechangelog/changelog.com/assets/14222322/da1432ce-9c89-46e9-bcda-92fb6fefc338)

**Comment by jerodsanto** [comment]
These are malware that are trying (and succeeding) to game the trending system. They have botnets that star their own repos.

If you check some of the recent commits on this repo you'll see me trying to add some rudimentary checks, but it's a cat and mouse game. This new account/repo/description format is pretty easy to detect, so I'll add that check to the list. But then they'll change it slightly so it doesn't match anymore and we'll be back where we are now...

Ideas welcome!

**Comment by jerodsanto** [comment]
Tracking work here via #46
