### ISSUE TITLE
Really pumped that this email is back and now the Changelog.

### ISSUE THREAD

**Issue by CameronBanga** [thechangelog/nightly#9]
This isn't really an issue, but I've really missed this nightly email. Glad it's back!

**Comment by adamstac** [comment]
Thanks for the shout out @CameronBanga we certainly appreciate the support. You should subscribe to Changelog Weekly too. We ship that on saturdays, but it's not automated -- it's highly curated and editorialized by myself and @jerodsanto.

Thanks for again for the shout and vote of confidence!

**Comment by adamstac** [comment]
Looking through the archives @CameronBanga and saw your repo CameronBanga/iOS-Developer-and-Designer-Interview-Questions here http://nightly.thechangelog.com/2015/01/02/

**Comment by CameronBanga** [comment]
@adamstac Just subscribed! 

That repo made me miss the newsletter the most. Was my one change to have fifteen minutes of Github fame. ;-)
